"""LumynaX CLI — the Ollama-class command-line for the 98-model LumynaX sovereign-AI release family from AbteeX AI Labs (Aotearoa New Zealand)."""
__version__ = "0.5.0"
HF_ORG = "AbteeXAILab"
REGISTRY_REPO = "AbteeXAILab/marama-route"
REGISTRY_PATH = "configs/lumynax_model_registry.json"
